// <auto-generated />
namespace Cloud_based_editor_VLN_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Content : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Content));
        
        string IMigrationMetadata.Id
        {
            get { return "201705040948555_Content"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
